### ISSUE TITLE
Uncaught TypeError: this.treeView.off is not a function

### ISSUE THREAD

**Issue by JerryWu1234** [hanyazou/tree-view-finder#13]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [tree-view-finder](https://github.com/hanyazou/tree-view-finder) package 0.2.1

### Stack Trace

Uncaught TypeError: this.treeView.off is not a function

```
At C:\Users\Administrator\.atom\packages\tree-view-finder\lib\tree-view-finder.coffee:177

TypeError: this.treeView.off is not a function
    at Object.hookTreeViewEvents (/packages/tree-view-finder/lib/tree-view-finder.coffee:177:15)
    at Object._show (/packages/tree-view-finder/lib/tree-view-finder.coffee:137:6)
    at Object.attach (/packages/tree-view-finder/lib/tree-view-finder.coffee:113:6)
    at /packages/tree-view-finder/lib/tree-view-finder.coffee:89:8)
    at HTMLBodyElement.dispatch (/packages/tree-view-finder/node_modules/jquery/dist/jquery.js:4737:27)
    at HTMLBodyElement.elemData.handle (/packages/tree-view-finder/node_modules/jquery/dist/jquery.js:4549:28)
    at Object.trigger (/packages/tree-view-finder/node_modules/jquery/dist/jquery.js:7807:12)
    at Object.simulate (/packages/tree-view-finder/node_modules/jquery/dist/jquery.js:7866:16)
    at HTMLDocument.handler (/packages/tree-view-finder/node_modules/jquery/dist/jquery.js:7925:17)
```

### Commands

```
  2x -5:05.2.0 core:backspace (input.hidden-input)
     -5:03.8.0 intentions:highlight (input.hidden-input)
     -5:03.7.0 core:save (input.hidden-input)
     -5:02.8.0 intentions:highlight (input.hidden-input)
  2x -5:02.7.0 core:copy (input.hidden-input)
     -5:01.3.0 intentions:highlight (input.hidden-input)
     -5:01.3.0 core:paste (input.hidden-input)
     -5:01.0 core:save (input.hidden-input)
     -3:40.3.0 intentions:highlight (input.hidden-input)
     -3:40.3.0 core:copy (input.hidden-input)
     -3:39.9.0 find-and-replace:show (input.hidden-input)
     -3:39.7.0 core:paste (input.hidden-input)
  6x -3:39.2.0 core:confirm (input.hidden-input)
  2x -3:15.6.0 core:backspace (input.hidden-input)
     -3:14.9.0 intentions:highlight (input.hidden-input)
     -3:14.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
atom-beautify 0.29.18 
atom-bootstrap3 1.2.12 
atom-html-preview 0.1.22 
atom-simplified-chinese-menu 0.6.5 
atom-ternjs 0.18.2 
autoclose-html 0.23.0 
autocomplete-css-with-stylus-support 1.0.0 
autocomplete-modules 1.6.9 
autocomplete-paths 1.0.5 
autoprefixer 3.6.1 
busy-signal 1.3.0 
csslint 1.1.5 
emmet 2.4.3 
file-icons 2.1.3 
file-types 0.5.5 
intentions 1.1.2 
jquery-snippets 11.0.0 
language-stylus 0.2.0 
language-vue 0.21.2 
language-vue-component 0.5.0 
linter 2.1.2 
linter-js-standard 3.9.0 
linter-ui-default 1.2.2 
minimap 4.27.1 
simplified-chinese-menu 3.5.0 
stylus-autocompile 0.6.1 
tree-view-finder 0.2.1 
vscode-snippets 0.1.3 
vue2-autocomplete 0.1.0-alpha.4 
vuejs2-snippets 0.8.0 
```

**Comment by zhkmxx9302013** [comment]
I ve got the same issue, on windows10 x64 Build 16716, and with python 3.5.3.

**Comment by williamnie** [comment]
我也发生了这个情况，请问你解决了吗

**Comment by JerryWu1234** [comment]
重启下好像就可以了，我也不懂为什么

**Comment by williamnie** [comment]
我的重启也不行，还是一直报错
C:\Users\hai\.atom\packages\tree-view-finder\lib\tree-view-finder.coffee:177
Hide Stack Trace
TypeError: this.treeView.off is not a function
    at Object.hookTreeViewEvents (file:///C:/Users/hai/.atom/packages/tree-view-finder/lib/tree-view-finder.coffee:177:15)
    at Object._show (file:///C:/Users/hai/.atom/packages/tree-view-finder/lib/tree-view-finder.coffee:137:6)
    at Object.attach (file:///C:/Users/hai/.atom/packages/tree-view-finder/lib/tree-view-finder.coffee:113:6)
    at HTMLOListElement.<anonymous> (file:///C:/Users/hai/.atom/packages/tree-view-finder/lib/tree-view-finder.coffee:89:8)
    at HTMLBodyElement.dispatch (C:\Users\hai\.atom\packages\tree-view-finder\node_modules\jquery\dist\jquery.js:4737:27)
    at HTMLBodyElement.elemData.handle (C:\Users\hai\.atom\packages\tree-view-finder\node_modules\jquery\dist\jquery.js:4549:28)
    at Object.trigger (C:\Users\hai\.atom\packages\tree-view-finder\node_modules\jquery\dist\jquery.js:7807:12)
    at Object.simulate (C:\Users\hai\.atom\packages\tree-view-finder\node_modules\jquery\dist\jquery.js:7866:16)
    at HTMLDocument.handler (C:\Users\hai\.atom\packages\tree-view-finder\node_modules\jquery\dist\jquery.js:7925:17)
