### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isVisible' of null

### ISSUE THREAD

**Issue by longfeey** [hanyazou/tree-view-finder#15]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0-beta5 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [tree-view-finder](https://github.com/hanyazou/tree-view-finder) package 0.2.1

### Stack Trace

Uncaught TypeError: Cannot read property 'isVisible' of null

```
At C:\Users\feilong.yan\.atom\packages\tree-view-finder\lib\tree-view-finder.coffee:105

TypeError: Cannot read property 'isVisible' of null
    at Object.toggle (/packages/tree-view-finder/lib/tree-view-finder.coffee:105:28)
    at /packages/tree-view-finder/lib/tree-view-finder.coffee:57:91)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.0-beta5/resources/app/src/command-registry.js:265:1)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.0-beta5/resources/app/src/command-registry.js:3:1)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.17.0-beta5/resources/app/src/command-registry.js:166:1)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.17.0-beta5/resources/app/src/atom-environment.js:1286:1)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.17.0-beta5/resources/app/src/application-delegate.js:334:1)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:45.3.0 snippets:show (input.hidden-input)
     -0:40.1.0 tree-view:toggle-focus (input.hidden-input)
  2x -0:34.8.0 tree-view:toggle (div.tool-panel.tree-view)
     -0:22.1.0 tree-view:toggle-side (div.tool-panel.tree-view)
     -0:18 tree-view-finder:toggle (div.tool-panel.tree-view)
```

### Non-Core Packages

```
atom-space-pen-views 2.2.0 
vim-mode-plus 0.92.0 
vim-mode-plus-ex-mode 0.9.0 
autocomplete-paths 1.0.5 
fs-plus 3.0.0 
fuzzaldrin 2.1.0 
git-plus 7.8.0 
jQuery 1.2.5 
minimap 4.28.2 
minimap-cursorline 0.2.0 
node-gyp 3.6.1 
package-sync 1.1.0 
Remote-FTP 0.10.7 
terminal-plus 0.14.5 
tree-view-finder 0.2.1 
```

**Comment by ironmaxtory** [comment]
This problem of the plugin showed on my atom too....

**Comment by fiker** [comment]
This problem of the plugin showed on my atom too....

**Comment by CodingQ** [comment]
This problem of the plugin showed on my atom too....

**Comment by Chiefss2** [comment]
so how to solve this problem finally?
