### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isVisible' of null

### ISSUE THREAD

**Issue by PrimaryKey3610** [hanyazou/tree-view-finder#17]
Uncaught TypeError: Cannot read property 'isVisible' of null
/Users/PrimaryKey/.atom/packages/tree-view-finder/lib/tree-view-finder.coffee:105
Hide Stack Trace
TypeError: Cannot read property 'isVisible' of null
    at Object.toggle (/Users/PrimaryKey/.atom/packages/tree-view-finder/lib/tree-view-finder.coffee:105:28)
    at HTMLElement.subscriptions.add.atom.commands.add.tree-view-finder:toggle (/Users/PrimaryKey/.atom/packages/tree-view-finder/lib/tree-view-finder.coffee:57:91)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
The error was thrown from the tree-view-finder package. This issue has already been reported.
View Issue

**Comment by SunmChan** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.0-beta2 ia32
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [tree-view-finder](https://github.com/hanyazou/tree-view-finder) package 0.2.1


### Stack Trace

Uncaught TypeError: Cannot read property 'isVisible' of null

```
At C:\Users\CHAN\.atom\packages\tree-view-finder\lib\tree-view-finder.coffee:105

TypeError: Cannot read property 'isVisible' of null
    at Object.toggle (/packages/tree-view-finder/lib/tree-view-finder.coffee:105:28)
    at /packages/tree-view-finder/lib/tree-view-finder.coffee:57:91)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (E:/GoogleDownloads/atom-windows/Atom Beta/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (E:/GoogleDownloads/atom-windows/Atom Beta/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (E:/GoogleDownloads/atom-windows/Atom Beta/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (E:/GoogleDownloads/atom-windows/Atom Beta/resources/app/src/atom-environment.js:1338:34)
    at EventEmitter.outerCallback (E:/GoogleDownloads/atom-windows/Atom Beta/resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:02.0 tree-view-finder:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atomic-chrome 0.3.2 
tree-view-finder 0.2.1 
```

**Comment by zhyd1997** [comment]
C:\Users\T-bao\.atom\packages\tree-view-finder\lib\tree-view-finder.coffee:105
Hide Stack Trace
TypeError: Cannot read property 'isVisible' of null
    at Object.toggle (file:///C:/Users/T-bao/.atom/packages/tree-view-finder/lib/tree-view-finder.coffee:105:28)
    at HTMLElement.subscriptions.add.atom.commands.add.tree-view-finder:toggle (file:///C:/Users/T-bao/.atom/packages/tree-view-finder/lib/tree-view-finder.coffee:57:91)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (G:\Atom\atom-x64-windows\Atom x64\resources\app\src\command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (G:\Atom\atom-x64-windows\Atom x64\resources\app\src\command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (G:\Atom\atom-x64-windows\Atom x64\resources\app\src\command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (G:\Atom\atom-x64-windows\Atom x64\resources\app\src\atom-environment.js:1338:34)
    at EventEmitter.outerCallback (G:\Atom\atom-x64-windows\Atom x64\resources\app\src\application-delegate.js:334:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
