### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isVisible' of null

### ISSUE THREAD

**Issue by FinKiin** [hanyazou/tree-view-finder#18]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [tree-view-finder](https://github.com/hanyazou/tree-view-finder) package 0.2.1

### Stack Trace

Uncaught TypeError: Cannot read property 'isVisible' of null

```
At C:\Users\Administrator\.atom\packages\tree-view-finder\lib\tree-view-finder.coffee:105

TypeError: Cannot read property 'isVisible' of null
    at Object.toggle (/packages/tree-view-finder/lib/tree-view-finder.coffee:105:28)
    at /packages/tree-view-finder/lib/tree-view-finder.coffee:57:91)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.22.0/resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.22.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.22.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.22.0/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.22.0/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -4:03.8.0 tree-view-finder:toggle (atom-pane.pane)
     -3:41.9.0 intentions:highlight (input.hidden-input)
     -3:41.5.0 tree-view-finder:toggle (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.6.0 
autoprefixer 3.7.1 
atom-beautify 0.30.6 
atom-clock 0.1.15 
file-types 0.5.5 
git-projects 1.17.0 
minimap-codeglance 0.4.7 
atom-ternjs 0.18.3 
autoclose-html 0.24.0 
autocomplete-paths 2.12.1 
busy-signal 1.4.3 
color-picker 2.2.5 
dracula-syntax 2.0.5 
dracula-ui 0.6.0 
emmet 2.4.3 
file-type-icons 1.3.4 
git-control 0.9.0 
git-plus 7.10.0 
intentions 1.1.5 
linter 2.2.0 
linter-csslint 2.0.0 
linter-js-standard 4.0.3 
linter-ui-default 1.6.10 
minimap 4.29.7 
open-in-browser 0.5.2 
Remote-FTP 1.3.1 
simplified-chinese-menu 5.3.5 
tree-view-finder 0.2.1 
```

**Comment by Mainyf** [comment]
null
