### ISSUE TITLE
Uncaught TypeError: path must be a string

### ISSUE THREAD

**Issue by iliekdags** [hanyazou/tree-view-finder#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: [tree-view-finder](https://github.com/hanyazou/tree-view-finder) package, v0.2.1
### Stack Trace

Uncaught TypeError: path must be a string

```
At fs.js:205

TypeError: path must be a string
  at TypeError (native)
  at fs.exists (fs.js:207:11)
  at Object.fs.exists (ATOM_SHELL_ASAR.js:286:16)
  at Object.module.exports.TreeViewFinder.openUri (/Users/whall/.atom/packages/tree-view-finder/lib/tree-view-finder.coffee:295:8)
  at Object.<anonymous> (/Users/whall/.atom/packages/tree-view-finder/lib/tree-view-finder.coffee:224:12)
  at Object.xor [as xorhandler] (/Users/whall/.atom/packages/tree-view-finder/lib/doubleTap.js/xorTap.js:46:13)
  at tree-view-file.<anonymous> (/Users/whall/.atom/packages/tree-view-finder/lib/tree-view-finder.coffee:243:10)
  at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```
### Commands

```
     -5:11.1.0 core:confirm (input.hidden-input)
     -5:09.0 core:paste (input.hidden-input)
     -5:04.5.0 core:undo (input.hidden-input)
     -4:59.8.0 core:paste (input.hidden-input)
     -4:14.1.0 core:select-all (input.hidden-input)
     -4:13.6.0 core:cut (input.hidden-input)
  2x -3:49.3.0 core:backspace (input.hidden-input)
  2x -3:41.9.0 core:confirm (input.hidden-input)
     -2:18.7.0 tree-view-finder:toggle (input.hidden-input)
     -2:00.6.0 tree-view:toggle (input.hidden-input)
     -1:48.5.0 tree-view:toggle-side (input.hidden-input)
     -1:43.7.0 tree-view:toggle (input.hidden-input)
     -0:31.3.0 core:cut (input.hidden-input)
     -0:21.5.0 core:paste (input.hidden-input)
     -0:20.4.0 core:save (input.hidden-input)
     -0:09.9.0 core:cut (input.hidden-input)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "term",
      "tree-view",
      "react",
      "atom-jade",
      "language-babel"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.3.0
color-picker, v2.0.4
git-projects, v1.14.1
linter, v0.12.7
linter-jshint, v0.1.6
php-twig, v4.0.0
project-manager, v1.15.10
remote-sync, v3.1.2
tree-view-finder, v0.2.1
tree-view-git-projects, v0.5.0

# Dev
No dev packages
```

**Comment by hanyazou** [comment]
I've updated my environment today. Now my env is very similar to yours. These version numbers are completely same. I guess you got the error on double click some item in the tree view. But I couldn't reproduce the error.

Atom Version: 0.209.0
System: Mac OS X 10.10.3
Thrown From: tree-view-finder package, v0.2.1

Could you tell me how/what did you do to get the error?
